import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuth } from '../App';
import Navbar from '../components/Navbar';
import LoadingSpinner from '../components/LoadingSpinner';
import axios from 'axios';
import './GovernmentInfo.css';

const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5001/api';

function GovernmentInfo() {
    const { t } = useTranslation();
    const { user } = useAuth();
    const [loading, setLoading] = useState(false);
    const [activeTab, setActiveTab] = useState('policies');
    const [data, setData] = useState(null);
    const [error, setError] = useState('');

    useEffect(() => {
        fetchComprehensiveData();
    }, []);

    const fetchComprehensiveData = async () => {
        setLoading(true);
        setError('');

        try {
            const token = localStorage.getItem('token');
            const response = await axios.get(`${API_URL}/government/ai/comprehensive`, {
                headers: {
                    'Authorization': `Bearer ${token}`
                }
            });

            setData(response.data);
        } catch (err) {
            console.error('Failed to fetch government info:', err);
            setError('Failed to load government information. Please try again later.');
        } finally {
            setLoading(false);
        }
    };

    if (loading) {
        return (
            <>
                <Navbar />
                <LoadingSpinner message="Loading government information..." />
            </>
        );
    }

    return (
        <div className="government-info-page">
            <Navbar />

            <div className="container govt-container">
                {/* Header */}
                <div className="govt-header">
                    <div>
                        <h1>🏛️ Government Information</h1>
                        <p className="text-secondary">
                            Policies, Schemes, Crop Prices & Resources for {user?.farmDetails?.location?.state}
                        </p>
                    </div>
                    <button className="btn btn-primary" onClick={fetchComprehensiveData}>
                        🔄 Refresh Data
                    </button>
                </div>

                {error && (
                    <div className="alert alert-error">
                        {error}
                    </div>
                )}

                {/* Tabs */}
                <div className="govt-tabs">
                    <button
                        className={`tab-btn ${activeTab === 'policies' ? 'active' : ''}`}
                        onClick={() => setActiveTab('policies')}
                    >
                        📋 Policies & Schemes
                    </button>
                    <button
                        className={`tab-btn ${activeTab === 'prices' ? 'active' : ''}`}
                        onClick={() => setActiveTab('prices')}
                    >
                        💰 Crop Prices
                    </button>
                    <button
                        className={`tab-btn ${activeTab === 'resources' ? 'active' : ''}`}
                        onClick={() => setActiveTab('resources')}
                    >
                        🔗 Resources & Websites
                    </button>
                </div>

                {/* Content */}
                <div className="govt-content">
                    {activeTab === 'policies' && data?.policies && (
                        <PoliciesTab policies={data.policies} />
                    )}
                    {activeTab === 'prices' && data?.prices && (
                        <PricesTab prices={data.prices} />
                    )}
                    {activeTab === 'resources' && data?.resources && (
                        <ResourcesTab resources={data.resources} />
                    )}
                </div>

                {/* Data Source */}
                {data && (
                    <div className="data-source">
                        <small>
                            ℹ️ Data generated by AI • Last updated: {new Date(data.generatedAt).toLocaleString()}
                            <br />
                            Please verify information with official sources before making decisions.
                        </small>
                    </div>
                )}
            </div>
        </div>
    );
}

// Policies Tab Component
function PoliciesTab({ policies }) {
    return (
        <div className="policies-tab">
            {/* Central Schemes */}
            <section className="info-section">
                <h2>🇮🇳 Central Government Schemes</h2>
                <div className="schemes-grid">
                    {policies.centralSchemes?.map((scheme, index) => (
                        <SchemeCard key={index} scheme={scheme} />
                    ))}
                </div>
            </section>

            {/* State Schemes */}
            <section className="info-section">
                <h2>📍 {policies.state} State Schemes</h2>
                <div className="schemes-grid">
                    {policies.stateSchemes?.map((scheme, index) => (
                        <SchemeCard key={index} scheme={scheme} />
                    ))}
                </div>
            </section>

            {/* Subsidies */}
            <section className="info-section">
                <h2>💸 Available Subsidies</h2>
                <div className="subsidies-list">
                    {policies.subsidies?.map((subsidy, index) => (
                        <div key={index} className="subsidy-card">
                            <div className="subsidy-header">
                                <h3>{subsidy.type}</h3>
                                <span className="amount-badge">{subsidy.amount}</span>
                            </div>
                            <p><strong>Applicable for:</strong> {subsidy.applicableFor}</p>
                            <p><strong>How to apply:</strong> {subsidy.howToApply}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Insurance & Loans */}
            <div className="grid grid-2">
                <section className="info-section">
                    <h2>🛡️ Crop Insurance</h2>
                    <div className="info-card">
                        <p><strong>Schemes:</strong> {policies.insurance?.schemes?.join(', ')}</p>
                        <p><strong>Coverage:</strong> {policies.insurance?.coverage}</p>
                        <p><strong>Premium:</strong> {policies.insurance?.premium}</p>
                        <p><strong>Claim Process:</strong> {policies.insurance?.claimProcess}</p>
                    </div>
                </section>

                <section className="info-section">
                    <h2>🏦 Agricultural Loans</h2>
                    <div className="info-card">
                        <p><strong>Schemes:</strong> {policies.loans?.schemes?.join(', ')}</p>
                        <p><strong>Interest Rate:</strong> {policies.loans?.interestRate}</p>
                        <p><strong>Maximum Amount:</strong> {policies.loans?.maximumAmount}</p>
                        <p><strong>Apply At:</strong> {policies.loans?.applyAt}</p>
                    </div>
                </section>
            </div>

            {/* Official Websites */}
            <section className="info-section">
                <h2>🌐 Official Websites</h2>
                <div className="websites-grid">
                    {policies.officialWebsites?.map((website, index) => (
                        <a
                            key={index}
                            href={website.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="website-card"
                        >
                            <h3>{website.name}</h3>
                            <p>{website.description}</p>
                            <span className="external-link">Visit →</span>
                        </a>
                    ))}
                </div>
            </section>
        </div>
    );
}

// Prices Tab Component
function PricesTab({ prices }) {
    const [searchTerm, setSearchTerm] = useState('');
    const [filterSeason, setFilterSeason] = useState('all');

    const filteredCrops = prices.crops?.filter(crop => {
        const matchesSearch = crop.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
            crop.hindiName?.includes(searchTerm);
        const matchesSeason = filterSeason === 'all' || crop.season === filterSeason;
        return matchesSearch && matchesSeason;
    });

    return (
        <div className="prices-tab">
            {/* Disclaimer */}
            <div className="disclaimer-box">
                ⚠️ {prices.disclaimer}
            </div>

            {/* Filters */}
            <div className="price-filters">
                <input
                    type="text"
                    placeholder="🔍 Search crops..."
                    value={searchTerm}
                    onChange={(e) => setSearchTerm(e.target.value)}
                    className="search-input"
                />
                <select
                    value={filterSeason}
                    onChange={(e) => setFilterSeason(e.target.value)}
                    className="season-filter"
                >
                    <option value="all">All Seasons</option>
                    <option value="Kharif">Kharif (Monsoon)</option>
                    <option value="Rabi">Rabi (Winter)</option>
                    <option value="Zaid">Zaid (Summer)</option>
                </select>
            </div>

            {/* Crops Table */}
            <div className="crops-table-container">
                <table className="crops-table">
                    <thead>
                        <tr>
                            <th>Crop Name</th>
                            <th>Current Price</th>
                            <th>MSP</th>
                            <th>Price Range</th>
                            <th>Trend</th>
                            <th>Season</th>
                            <th>Market Demand</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredCrops?.map((crop, index) => (
                            <tr key={index}>
                                <td>
                                    <div className="crop-name">
                                        <strong>{crop.name}</strong>
                                        <small>{crop.hindiName}</small>
                                    </div>
                                </td>
                                <td className="price-cell">₹{crop.currentPrice}</td>
                                <td className="msp-cell">{crop.msp}</td>
                                <td>{crop.priceRange}</td>
                                <td>
                                    <span className={`trend-badge trend-${crop.trend}`}>
                                        {crop.trend === 'increasing' && '📈'}
                                        {crop.trend === 'stable' && '➡️'}
                                        {crop.trend === 'decreasing' && '📉'}
                                        {crop.trend}
                                    </span>
                                </td>
                                <td>{crop.season}</td>
                                <td>
                                    <span className={`demand-badge demand-${crop.marketDemand}`}>
                                        {crop.marketDemand}
                                    </span>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Markets */}
            <section className="info-section">
                <h2>🏪 Major Markets (Mandis)</h2>
                <div className="markets-grid">
                    {prices.markets?.map((market, index) => (
                        <div key={index} className="market-card">
                            <h3>{market.name}</h3>
                            <p><strong>Location:</strong> {market.location}</p>
                            <p><strong>Type:</strong> {market.type}</p>
                            <div className="facilities">
                                {market.facilities?.map((facility, i) => (
                                    <span key={i} className="facility-tag">{facility}</span>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            {/* Online Resources */}
            <section className="info-section">
                <h2>🌐 Online Price Checking Platforms</h2>
                <div className="resources-grid">
                    {prices.onlineResources?.map((resource, index) => (
                        <a
                            key={index}
                            href={resource.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="resource-card"
                        >
                            <h3>{resource.name}</h3>
                            <p>{resource.features}</p>
                            <small>Coverage: {resource.coverage}</small>
                            <span className="external-link">Visit →</span>
                        </a>
                    ))}
                </div>
            </section>

            {/* Market Info */}
            {prices.marketInfo && (
                <div className="market-info-box">
                    <h3>📊 Market Advisory</h3>
                    <p><strong>Peak Season:</strong> {prices.marketInfo.peakSeason}</p>
                    <p><strong>Advisory:</strong> {prices.marketInfo.advisory}</p>
                    <p><strong>Contacts:</strong> {prices.marketInfo.contacts}</p>
                </div>
            )}
        </div>
    );
}

// Resources Tab Component
function ResourcesTab({ resources }) {
    return (
        <div className="resources-tab">
            {/* Departments */}
            <section className="info-section">
                <h2>🏢 Government Departments</h2>
                <div className="departments-grid">
                    {resources.departments?.map((dept, index) => (
                        <div key={index} className="dept-card">
                            <h3>{dept.name}</h3>
                            <div className="services-list">
                                {dept.services?.map((service, i) => (
                                    <span key={i} className="service-tag">✓ {service}</span>
                                ))}
                            </div>
                            <p className="contact-info">📞 {dept.contact}</p>
                            {dept.website && (
                                <a href={dept.website} target="_blank" rel="noopener noreferrer" className="dept-link">
                                    Visit Website →
                                </a>
                            )}
                        </div>
                    ))}
                </div>
            </section>

            {/* E-Governance Portals */}
            <section className="info-section">
                <h2>💻 E-Governance Portals</h2>
                <div className="portals-grid">
                    {resources.eGovernance?.map((portal, index) => (
                        <a
                            key={index}
                            href={portal.url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="portal-card"
                        >
                            <h3>{portal.name}</h3>
                            <p>{portal.purpose}</p>
                            <small><strong>How to Register:</strong> {portal.howToRegister}</small>
                            <span className="external-link">Open Portal →</span>
                        </a>
                    ))}
                </div>
            </section>

            {/* Institutions */}
            <section className="info-section">
                <h2>🎓 Agricultural Institutions</h2>
                <div className="institutions-list">
                    {resources.institutions?.map((inst, index) => (
                        <div key={index} className="institution-card">
                            <div className="inst-header">
                                <h3>{inst.name}</h3>
                                <span className="inst-type">{inst.type}</span>
                            </div>
                            <p><strong>Location:</strong> {inst.location}</p>
                            <div className="services-list">
                                {inst.services?.map((service, i) => (
                                    <span key={i} className="service-tag">{service}</span>
                                ))}
                            </div>
                            <p className="contact-info">{inst.contact}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Helplines */}
            <section className="info-section">
                <h2>📞 Farmer Helplines</h2>
                <div className="helplines-grid">
                    {resources.helplines?.map((helpline, index) => (
                        <div key={index} className="helpline-card">
                            <h3>{helpline.name}</h3>
                            <div className="helpline-number">{helpline.number}</div>
                            <p><strong>Available:</strong> {helpline.availability}</p>
                            <p><strong>Languages:</strong> {helpline.languages?.join(', ')}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Mobile Apps */}
            <section className="info-section">
                <h2>📱 Useful Mobile Apps</h2>
                <div className="apps-grid">
                    {resources.mobileApps?.map((app, index) => (
                        <div key={index} className="app-card">
                            <h3>{app.name}</h3>
                            <p>{app.purpose}</p>
                            <div className="app-footer">
                                <span className="platform-badge">{app.platform}</span>
                                {app.downloadLink !== 'N/A' && (
                                    <a href={app.downloadLink} target="_blank" rel="noopener noreferrer">
                                        Download
                                    </a>
                                )}
                            </div>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    );
}

// Scheme Card Component
function SchemeCard({ scheme }) {
    return (
        <div className="scheme-card">
            <h3>{scheme.name}</h3>
            <p className="scheme-desc">{scheme.description}</p>
            <div className="scheme-details">
                <p><strong>Eligibility:</strong> {scheme.eligibility}</p>
                <p><strong>Benefits:</strong> {scheme.benefits}</p>
            </div>
            {scheme.website && (
                <a href={scheme.website} target="_blank" rel="noopener noreferrer" className="scheme-link">
                    Learn More →
                </a>
            )}
        </div>
    );
}

export default GovernmentInfo;
